version: '3'

tasks:
  build:
    sources:
      - src/index.pug
      - src/components/**/*.pug
      - src/scss/*.scss
      - src/scss/**/*.scss
    cmds:
      - rm -rf public
      # - mv .git .git.bk #Plugins doesn't work if a have a .git in a subdir
      - bunx parcel build {{.TASKFILE_DIR}}/src/*.pug --dist-dir {{.TASKFILE_DIR}}/public --no-source-maps --no-cache --public-url .
      # - mv .git.bk .git #I'm investigating why
      - task: format
        vars: { SUB_DIR: public/ }

  dev:
    cmds:
      - bunx parcel src/index.pug --dist-dir dist --no-source-maps --host 0.0.0.0

  deploy:
    deps: [build]
    cmds:
      - git subtree push --prefix public origin deploy

  setup_deploy:
    cmds:
      - git push origin deploy:deploy

  format:
    sources:
      - public/*.html
      - public/*.css
    cmds:
      - prettier {{.ROOT_DIR}}/{{.SUB_DIR}} --write --config ../../.prettierrc
