version: '3'

tasks:
  build:
    sources:
      - index.pug
      - includes/*.pug
      - assets/scss/*.scss
    cmds:
      - yarn parcel build {{.TASKFILE_DIR}}/*.pug --dist-dir {{.TASKFILE_DIR}}/dist --no-source-maps --no-optimize

  dev:
    cmds:
      - yarn parcel {{.TASKFILE_DIR}}/index.pug --dist-dir {{.TASKFILE_DIR}}/dist --no-source-maps
    # depends on setup - git branch deploy
    sources:
      - dist/

  public:
    deps: [build]
    sources:
      - dist/*
    cmds:
      - rm -r public/*
      - cp -r dist/* public/
      - task: format
        vars: { SUB_DIR: public/ }

      # - git subtree push --prefix public origin -u deploy

      #setup predeploy create remote branch deploy and sources in public

  deploy:
    deps: [public, setup_deploy]
    cmds:
      - git subtree push --prefix public origin -u deploy

  setup_deploy:
    cmds:
      - git push origin deploy:deploy

  format:
    sources:
      - public/*.html
      - public/*.css
    cmds:
      - prettier {{.ROOT_DIR}}/{{.SUB_DIR}} --write --config ../../.prettierrc
